---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container-reg-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: registry-pod
  labels:
    name: pigeon-registry
spec:
  containers:
  - name: dockerhub
    image: docker.io/registry
    env:
    - name: REGISTRY_HTTP_ADDR
      value: 0.0.0.0:5000
    - name: REGISTRY_HTTP_TLS_CERTIFICATE
      value: /cer/tls.crt
    - name: REGISTRY_HTTP_TLS_KEY
      value: /cer/tls.key
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: container-vol
      mountPath: /var/lib/registry
    - name: certs
      mountPath: /cer
  volumes:
  - name: container-vol
    persistentVolumeClaim:
      claimName: container-reg-pvc
  - name: certs
    secret:
      secretName: pigeon-registry 
---
apiVersion: v1
kind: Service
metadata:
  name: registry-svc
spec:
  type: NodePort
  selector:
    name: pigeon-registry
  ports:
  - name: registry-svc
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32500