apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pigeons.tbkb.info
spec:
  group: tbkb.info
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required:
          - app-name
          - git-repo
          - service-port
        properties:
          spec:
            type: object
            properties:
              app-name:
                type: string
              git-repo:
                type: string
              service-port:
                type: integer
              git-repo-secret:
                type: string
  scope: Namespaced
  names:
    plural: pigeons
    singular: pigeon
    kind: Pigeon