---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ pig_name }}
  labels:
    name: {{ pig_name }}
  namespace: {{ namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ pig_name }}
  template:
    metadata:
      labels:
        app: {{ pig_name }}
    spec:
      containers:
      - name: {{ pig_name }}
        image: localhost:32500/{{ pig_name }}
      initContainers:
      - name: init-pigeon
        image: docker.io/tjbredow/pigeon-init
        command: ["/opt/cloneandstore.sh","{{ git_repo }}","{{ pig_name }}"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: p-cache
          mountPath: /var/lib/containers
      volumes:
      - name: p-cache
        persistentVolumeClaim:
          claimName: pigeon-cache-pvc 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ pig_name }}
  namespace: {{ namespace }}
spec:
  type: NodePort
  selector:
    app: {{ pig_name }}
  ports:
  - name: {{pig_name}}-svc
    protocol: TCP
    port: {{container_port}}
    targetPort: {{container_port}}