apiVersion: v1
kind: ServiceAccount
metadata:
  name: pigeon-acc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pigeon-cache-pvc
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pigeon
rules:
  - apiGroups: ["tbkb.info"]
    resources: ["pigeons"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps","deployments","services","ingresses"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pigeon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pigeon
subjects:
- kind: ServiceAccount
  name: pigeon-acc
  namespace: default
---
apiVersion: v1
kind: Deployment
metadata:
  name: pigeon-operator
  labels:
    name: pigeon-operator
spec:
  replcias: 1
  template:
    spec:
      containers:
      - name: pigeon-operator
        image: docker.io/tjbredow/pigeon-operator
      serviceAccountName: pigeon-acc